spring:
  config:
    activate:
      on-profile: prod

rabbitmq:
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  virtual-host: ${RABBITMQ_VIRTUAL_HOST}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: dev

rabbitmq:
  host: ${RABBITMQ_STOMP_HOST}
  port: ${RABBITMQ_STOMP_PORT}
  username: ${RABBITMQ_STOMP_USERNAME}
  password: ${RABBITMQ_STOMP_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: local

rabbitmq:
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  virtual-host: ${RABBITMQ_VIRTUAL_HOST}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}
